# Generated by Django 5.2.5 on 2025-08-20 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailmodel',
            name='email',
            field=models.EmailField(max_length=254),
        ),
    ]
